#! /bin/bash

scons TARGET_OS=android TARGET_ARCH=armeabi-v7a TARGET_TRANSPORT=ALL LOGGING=yes VERBOSE=yes
scons TARGET_OS=android TARGET_ARCH=armeabi TARGET_TRANSPORT=ALL LOGGING=yes VERBOSE=yes
scons TARGET_OS=android TARGET_ARCH=x86 TARGET_TRANSPORT=ALL LOGGING=yes VERBOSE=yes
scons TARGET_OS=android TARGET_ARCH=x86_64 TARGET_TRANSPORT=ALL LOGGING=yes VERBOSE=yes
