#! /bin/bash

scons TARGET_OS=android RELEASE=yes TARGET_ARCH=armeabi-v7a TARGET_TRANSPORT=ALL LOGGING=no VERBOSE=no
scons TARGET_OS=android RELEASE=yes TARGET_ARCH=armeabi TARGET_TRANSPORT=ALL LOGGING=no VERBOSE=no
scons TARGET_OS=android RELEASE=yes TARGET_ARCH=x86 TARGET_TRANSPORT=ALL LOGGING=no VERBOSE=no
scons TARGET_OS=android RELEASE=yes TARGET_ARCH=x86_64 TARGET_TRANSPORT=ALL LOGGING=no VERBOSE=no
